### ISSUE TITLE
Tracking updates on dependencies

### ISSUE THREAD

**Issue by somehowchris** [kurtlawrence/guid-create#7]
As of right now, from time to time, dependencies were updated.

There aren't a lot but it would be nice from a sec and maintenance perspective to track updates on dependencies and from time to time, release a new version once they have been updated on the `Cargo.toml`.

From my experience, `dependabot` is the bot from GitHub configured via a yaml file but I prefer `renovate` a git distro independent and open source one and integrated into GitHub via a app on the marketplace. Renovate will automatically detect which package managers and where they are used. https://github.com/marketplace/renovate

In the end its up to you @kurtlawrence

**Comment by kurtlawrence** [comment]
I've never used either personally, but I am willing to give them a go.
I'll let you implement if you'd like @somehowchris?

**Comment by somehowchris** [comment]
Well its literally up to you 😅 

Since this repo is hosted under your account, you're the only one able to setup apps for it. Just jump [here to the marketplace](https://github.com/marketplace/renovate) click `Setup a new plan`, select this repository and off you go. Renovate will open up a pr to create a configuration. It will also open up a tracking issue as a general list of updates pending which it will update once there are updates.

**Comment by kurtlawrence** [comment]
Alright, #8 enables renovate!
